sudo : required
services: 
   - docker


before_install:
   - docker build -t tato/react-test -f ./client/Dockerfile.dev ./client

script:
   - docker run tato/react-test npm test -- --coverage

after_success:
   - docker build -t tatocar/multi-client ./client
   - docker build -t tatocar/multi-nginx ./nginx
   - docker build -t tatocar/multi-server ./server
   - docker build -t tatocar/multi-worker ./worker
   # Log in to the docker CLI
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   # Take those images and push them to docker hub
   - docker push tatocar/multi-client
   - docker push tatocar/multi-nginx
   - docker push tatocar/multi-server
   - docker push tatocar/multi-worker
